# Generated by Django 5.0.4 on 2025-01-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_user_bio_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default-product.png', upload_to='userimage/'),
        ),
    ]
