# Generated by Django 5.0.4 on 2025-01-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default-avatar-profile-.webp', upload_to='userimage/'),
        ),
    ]
