# Generated by Django 5.0.4 on 2025-01-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
